# knowledge/schema/versions.py
"""统一版本号。每个产物必须记录其 schema/analyzer 版本，保证可复现与可追溯。"""

# 语料处理
CLEANER_VERSION = "0.1.0"
CHUNKER_VERSION = "0.1.0"

# Schema
SCHEMA_VERSION = "0.1.0"
FEATURE_SCHEMA_VERSION = "0.1.0"
NARRATIVE_SCHEMA_VERSION = "0.1.0"
STRATEGY_SCHEMA_VERSION = "0.1.0"
STYLOMETRY_SCHEMA_VERSION = "0.1.0"

# Analyzer（与 schema_version 分离，见 spec §17.6）
STATISTICAL_ANALYZER_VERSION = "0.1.0"
LLM_ANALYZER_VERSION = "0.1.0"
NARRATIVE_ANALYZER_VERSION = "0.1.0"
STRATEGY_MINER_VERSION = "0.1.0"
STYLOMETRY_VERSION = "0.1.0"
AGGREGATION_VERSION = "0.1.0"
SAMPLING_VERSION = "0.1.0"
